// All site copy, English + Spanish. Keep both objects in the same shape.

const en = {
  meta: {
    title: 'Jordi Facha Álvarez — Engineering Student & Podcaster',
    podcastTitle: 'Inside The Machine — Jordi Facha Álvarez',
    clubTitle: 'Investing — Jordi Facha Álvarez',
    servicesTitle: 'Services & Community — Jordi Facha Álvarez',
  },
  nav: {
    about: 'About',
    journey: 'Journey',
    projects: 'Projects',
    podcast: 'Podcast',
    contact: 'Contact',
    cta: 'Get in touch',
    menu: 'Open menu',
    close: 'Close menu',
    back: 'Back to portfolio',
    allProjects: 'All projects',
    menuPodcast: 'Inside The Machine',
    menuPodcastDesc: 'Motorsport & engineering podcast',
    menuClub: 'Investing',
    menuClubDesc: 'My portfolio & approach',
    menuPaper: 'Aerodynamics paper',
    menuPaperDesc: 'IB research · PDF',
    menuCommunity: 'Community & charity',
    menuCommunityDesc: 'Global Citizens Club & more',
    themeLight: 'Switch to light mode',
    themeDark: 'Switch to dark mode',
  },
  photo: {
    label: 'Photo to add',
  },
  hero: {
    eyebrow: 'Engineering + Business · UFV Madrid',
    line1: 'Hi, I’m Jordi.',
    line2: 'Engineering what moves.',
    sub: 'Automotive & Industrial Engineering student with a Minor in Business Management at Universidad Francisco de Vitoria — and host of Inside The Machine, a podcast on the engineering, design and people behind motorsport.',
    ctaPrimary: 'Watch the podcast',
    ctaSecondary: 'LinkedIn',
    live: 'New',
    scroll: 'Scroll',
    photoTitle: 'Hero portrait',
    photoDesc: 'You in a race suit or casual jacket next to a car or kart, shot from a slightly low angle at golden hour. Vertical 4:5, with you on one side and some empty space around you.',
  },
  about: {
    eyebrow: 'About me',
    title: 'Always learning —',
    titleItalic: 'anything and everything.',
    p: [
      'Learning has always been the driving force behind everything I do — I love learning anything and everything I can, about any subject, and understanding how things really work. That mindset has shaped my path into studying Automotive and Industrial Engineering, with a Minor in Business Management, at Universidad Francisco de Vitoria in Madrid, as well as pursuing challenges beyond the classroom. From completing the IB Diploma with Higher Level Physics, Chemistry and Business Management to learning five languages and launching a motorsport podcast where I speak with people inside the industry, I’ve consistently sought out opportunities to keep learning.',
      'Having lived in three countries early in life and grown up between Spanish and Mexican cultures, I’ve developed a broad perspective that shapes how I approach ideas and challenges. Being surrounded by people from a wide range of professional backgrounds has also exposed me to different ways of thinking and problem-solving from an early age.',
      'Beyond academics, I’m driven by the idea of creating something meaningful. Whether it’s founding an AI-focused investment club, working alongside charities, or competing in football and karting, I value discipline, curiosity, and continuous improvement. These experiences have reinforced my belief in contributing to something larger than myself.',
      'Looking ahead, my ambition is simple: to build, to innovate, and to leave a lasting impact.',
    ],
    sign: 'Sincerely,',
    toolkitTitle: 'Toolkit',
    toolkit: [
      { group: 'Engineering', items: ['Aerodynamics', 'Engineering thinking', 'Experimentation'] },
      { group: 'Business', items: ['Business management', 'Investment analysis', 'Project management'] },
      { group: 'Communication', items: ['Technical communication', 'Interviewing', 'Five languages'] },
    ],
  },
  features: {
    eyebrow: 'What I do',
    title: 'Three things',
    titleItalic: 'that drive me.',
    sub: 'Learning from the people behind the machines, understanding the physics that makes them fast, and fitting it all around an engineering degree.',
    podcast: {
      tag: 'Podcast',
      title: 'Inside The Machine',
      desc: 'Long-form conversations with drivers, collectors, designers and engineers — in English and Spanish.',
      bullets: ['7 episodes and counting', 'Guests incl. Enzo Fittipaldi', 'YouTube · Spotify · TikTok'],
    },
    aero: {
      tag: 'Aerodynamics',
      title: 'Research & engineering',
      desc: 'My IB research paper measured how rear wing length changes downforce on a model Porsche 911 RSR.',
      bullets: ['Controlled experiments', 'Applied physics', 'Read the full paper'],
      header: 'Airflow · rear wing',
      states: ['Measuring downforce', 'Adjusting wing length', 'Flow attached', 'Logging results'],
    },
    now: {
      tag: 'Right now',
      title: 'Studies + studio',
      desc: 'Engineering and business lectures at UFV during the week, recording and editing the next episode in between.',
      bullets: ['Engineering + Business minor', 'Ep. 7 in production', 'Investing on the side'],
      week: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
      lecture: 'Lectures',
      record: 'Recording',
      booked: 'Ep. 7 session booked',
      picking: 'Planning the week…',
    },
  },
  pillars: {
    eyebrow: 'By the numbers',
    items: [
      { label: 'Podcast episodes', end: 7, suffix: '', desc: 'From Episode 0 in January to Monterey Car Week — with guests from Mexico, the US and beyond.' },
      { label: 'Languages', end: 5, suffix: '', desc: 'Grown up between Spanish and Mexican cultures, having lived in three countries early in life.' },
      { label: 'Years of community work', end: 10, suffix: '+', desc: 'Clubs, charities and foundations — including serving as President of the Global Citizens Club.' },
    ],
  },
  journey: {
    eyebrow: 'My journey',
    title: 'Three countries,',
    titleItalic: 'one constant: learning.',
    sub: 'Four schools across Mexico, Spain and Switzerland — every move a new language, a new culture and a new way of seeing things.',
    stops: [
      {
        flag: '🇲🇽',
        place: 'Mexico City, Mexico',
        chip: 'Mexico City',
        span: '8',
        unit: 'years',
        school: 'The American School Foundation',
        desc: 'Where it all started. Eight years growing up between Spanish and Mexican cultures — the roots of the perspective I bring to everything.',
        photoDesc: 'A photo from your years in Mexico — at ASF, in Mexico City, or an old family photo.',
      },
      {
        flag: '🇪🇸',
        place: 'Madrid, Spain',
        chip: 'Madrid',
        span: '6',
        unit: 'years',
        school: 'American School of Madrid',
        desc: 'A new city and a new chapter. Six years in Madrid, building friendships, routines and the interests that still drive me today.',
        photoDesc: 'You in Madrid or at ASM during those years.',
      },
      {
        flag: '🇨🇭',
        place: 'Leysin, Switzerland',
        chip: 'Leysin',
        span: '1',
        unit: 'year',
        school: 'Leysin American School',
        desc: 'A year at boarding school in the Swiss Alps — living independently, surrounded by students from all over the world.',
        photoDesc: 'You in Leysin — the campus, the mountains, or with classmates.',
      },
      {
        flag: '🇪🇸',
        place: 'Back in Madrid',
        chip: 'Madrid',
        span: 'IB',
        unit: 'Diploma',
        school: 'American School of Madrid',
        desc: 'Came back to Madrid and completed the IB Diploma with Higher Level Physics, Chemistry and Business Management — including my aerodynamics research paper.',
        link: 'Read the research paper',
        photoDesc: 'Your IB graduation, or the model Porsche 911 RSR from your research paper.',
      },
      {
        flag: '🎓',
        place: 'Madrid, Spain · Now',
        chip: 'UFV',
        span: 'UFV',
        unit: 'Now',
        now: true,
        school: 'Universidad Francisco de Vitoria',
        desc: 'Studying Automotive & Industrial Engineering with a Minor in Business Management — while building Inside The Machine and managing my own investment portfolio alongside it.',
      },
    ],
  },
  projects: {
    eyebrow: 'Projects',
    title: 'What I’m',
    titleItalic: 'building.',
    sub: 'Real projects that show my interests and what I’m capable of creating.',
    open: 'Open',
    items: [
      { key: 'podcast', title: 'Inside The Machine Podcast', desc: 'How engineering, design and aerodynamics shape the performance and identity of cars — from road vehicles to race machines — told through the people inside motorsport.', tags: ['Audio', 'Video', 'Interviews'] },
      { key: 'paper', title: 'Aerodynamics Research Paper', desc: 'My IB Extended Essay rigorously investigated the impact of rear wing length on downforce in a model Porsche 911 RSR, combining aerodynamic theory with controlled experimentation.', tags: ['Aerodynamics', 'Motorsport', 'Applied Physics'] },
      { key: 'club', title: 'Investing', desc: 'What began as an AI-focused investment club I founded is now my own long-term portfolio — researching companies across sectors and geographies, and learning from every decision.', tags: ['Investing', 'Analysis', 'Strategy'] },
      { key: 'services', title: 'Global Citizens Club & Charity', desc: 'Over a decade of clubs, charitable initiatives and foundations — including serving as President of the Global Citizens Club, connecting students with global causes and their local community.', tags: ['Leadership', 'Charity', 'Community'] },
      { key: 'sport', title: 'Karting & Football', desc: 'Competing on track and on the pitch — where discipline, focus and a competitive mindset get tested every week.', tags: ['Motorsport', 'Teamwork', 'Competition'] },
    ],
  },
  contact: {
    eyebrow: 'Contact',
    title: 'Let’s',
    titleItalic: 'talk.',
    sub: 'An idea, a collaboration, a guest suggestion for the podcast — or just to say hi.',
    emailLabel: 'Email',
    linkedinLabel: 'LinkedIn',
    instagramLabel: 'Instagram',
    note: 'Pressing send opens your email app with the message ready to go.',
    name: 'Name',
    namePh: 'Your name',
    email: 'Email',
    emailPh: 'you@email.com',
    message: 'Message',
    messagePh: 'What would you like to talk about?',
    send: 'Send message',
    sending: 'Opening your email…',
    sentTitle: 'Almost there.',
    sentDesc: 'Your email app should have opened with the message ready — just hit send there.',
    again: 'Write another message',
    missing: 'Please fill in all fields.',
  },
  footer: {
    tagline: 'Automotive & Industrial Engineering student and host of Inside The Machine.',
    status: 'Currently studying at UFV · Madrid',
    explore: 'Explore',
    club: 'Investing',
    podcast: 'Podcast',
    connect: 'Connect',
    rights: 'All rights reserved.',
    made: 'Always learning · Madrid',
  },
  podcastPage: {
    eyebrow: 'Podcast · Hosted by Jordi Facha Álvarez',
    line1: 'Inside',
    line2: 'The Machine.',
    sub: 'Exploring how engineering, design and aerodynamics shape the performance and identity of cars — from road vehicles to race machines — while speaking with the people inside the motorsport world.',
    watch: 'Watch on YouTube',
    listen: 'Listen on Spotify',
    chips: ['7 episodes', 'English & Español'],
    newChip: 'New: Ep. 6 — Monterey Car Week',
    aboutEyebrow: 'About the show',
    aboutTitle: 'Where motorsport',
    aboutTitleItalic: 'meets engineering.',
    aboutP: [
      'Inside The Machine pulls back the curtain on motorsport and car culture. Every episode digs into the technical side — the aerodynamics, the engineering decisions and the design philosophies that separate fast cars from championship-winning ones.',
      'Beyond the machines, the show features the people who live it: a three-time Carrera Panamericana winner, professional racing drivers, Ferrari collectors, automotive designers and mechanics-turned-racers.',
    ],
    stats: [
      { end: 7, suffix: '', label: 'Episodes released' },
      { end: 5, suffix: '', label: 'Guests from inside the industry' },
      { end: 2, suffix: '', label: 'Languages — English & Español' },
    ],
    latestEyebrow: 'New episode',
    latestTitle: 'The latest',
    latestTitleItalic: 'episode.',
    episodeLabel: 'Episode',
    watchYt: 'Watch on YouTube',
    listenSp: 'Listen on Spotify',
    archiveEyebrow: 'Every episode',
    archiveTitle: 'The full',
    archiveTitleItalic: 'archive.',
    archiveSub: 'The three most recent episodes — open the full list for every conversation since Episode 0.',
    showAll: 'Show all episodes',
    hideAll: 'Show fewer episodes',
    followEyebrow: 'Find us on',
    followTitle: 'Listen &',
    followTitleItalic: 'follow.',
    platforms: {
      youtube: 'Full episodes & shorts',
      spotify: 'Inside The Machine Podcast',
      tiktok: 'Clips & highlights',
      instagram: '@inside_the_machine_',
      email: 'Guest & partnership enquiries',
    },
    playTitle: 'Press',
    playTitleItalic: 'play.',
    mosaicLabel: 'Latest episodes',
  },
  clubPage: {
    eyebrow: 'Investing',
    line1: 'Investing in',
    line2: 'the future.',
    sub: 'I invest for the long term. It started as an AI-focused investment club I founded; today I manage my own portfolio — diversified across sectors and geographies, and built on understanding every company I own.',
    allocEyebrow: 'Portfolio allocation',
    allocTitle: 'Current',
    allocTitleItalic: 'breakdown.',
    total: 'Total',
    categories: {
      growth: 'Growth / Speculative',
      value: 'Value / Dividends',
      etf: 'ETFs',
      tech: 'Large Cap Tech',
    },
    disclaimer: 'The following are some of the companies in my portfolio, selected to illustrate its diversity across sectors and geographies. They are not necessarily my highest-yielding positions or largest holdings by weight — simply a snapshot of the range of opportunities I’ve invested in.',
    notable: 'Notable holdings',
    viewAll: 'View full portfolio',
    hideAll: 'Hide full portfolio',
  },
  servicesPage: {
    eyebrow: 'Global Citizens Club & Charity',
    line1: 'Building things',
    line2: 'that matter.',
    sub: 'Over a decade of involvement in clubs, charitable initiatives and foundations, including serving as President of the Global Citizens Club. This page will showcase that work.',
    soonTag: 'Coming soon',
    soonTitle: 'This page is being built.',
    soonDesc: 'Check back soon to learn more about the charitable work, initiatives and community projects I’ve been part of.',
    back: 'Back to portfolio',
    photos: [
      { title: 'Global Citizens Club', desc: 'You leading a club meeting or event — speaking, or with the team around you. Horizontal 4:3.' },
      { title: 'Charity work', desc: 'You volunteering at one of the charities or foundations — hands-on, candid, faces visible. Horizontal 4:3.' },
    ],
  },
}

const es = {
  meta: {
    title: 'Jordi Facha Álvarez — Estudiante de Ingeniería y Podcaster',
    podcastTitle: 'Inside The Machine — Jordi Facha Álvarez',
    clubTitle: 'Inversión — Jordi Facha Álvarez',
    servicesTitle: 'Servicios y Comunidad — Jordi Facha Álvarez',
  },
  nav: {
    about: 'Sobre mí',
    journey: 'Trayectoria',
    projects: 'Proyectos',
    podcast: 'Podcast',
    contact: 'Contacto',
    cta: 'Contáctame',
    menu: 'Abrir menú',
    close: 'Cerrar menú',
    back: 'Volver al portfolio',
    allProjects: 'Todos los proyectos',
    menuPodcast: 'Inside The Machine',
    menuPodcastDesc: 'Podcast de motor e ingeniería',
    menuClub: 'Inversión',
    menuClubDesc: 'Mi cartera y mi enfoque',
    menuPaper: 'Trabajo de aerodinámica',
    menuPaperDesc: 'Investigación IB · PDF',
    menuCommunity: 'Comunidad y voluntariado',
    menuCommunityDesc: 'Global Citizens Club y más',
    themeLight: 'Cambiar a modo claro',
    themeDark: 'Cambiar a modo oscuro',
  },
  photo: {
    label: 'Foto pendiente',
  },
  hero: {
    eyebrow: 'Ingeniería + Empresa · UFV Madrid',
    line1: 'Hola, soy Jordi.',
    line2: 'Ingeniería en movimiento.',
    sub: 'Estudiante de Ingeniería en Automoción e Industrial con un Minor en Administración de Empresas en la Universidad Francisco de Vitoria, y presentador de Inside The Machine, un podcast sobre la ingeniería, el diseño y las personas detrás del motor.',
    ctaPrimary: 'Ver el podcast',
    ctaSecondary: 'LinkedIn',
    live: 'Nuevo',
    scroll: 'Desliza',
    photoTitle: 'Retrato principal',
    photoDesc: 'Tú con mono de carreras o chaqueta informal junto a un coche o kart, desde un ángulo ligeramente bajo y con luz de atardecer. Vertical 4:5, contigo a un lado y algo de espacio libre alrededor.',
  },
  about: {
    eyebrow: 'Sobre mí',
    title: 'Siempre aprendiendo:',
    titleItalic: 'de todo y sobre todo.',
    p: [
      'Aprender siempre ha sido el motor de todo lo que hago: me encanta aprender todo lo que puedo, sobre cualquier tema, y entender cómo funcionan realmente las cosas. Esa mentalidad me ha llevado a estudiar Ingeniería en Automoción e Industrial, con un Minor en Administración de Empresas, en la Universidad Francisco de Vitoria, en Madrid, y a buscar retos más allá de las aulas. Desde completar el Bachillerato Internacional con Física, Química y Gestión Empresarial de Nivel Superior hasta aprender cinco idiomas y lanzar un podcast de motor en el que hablo con personas de dentro de la industria, siempre he buscado oportunidades para seguir aprendiendo.',
      'Haber vivido en tres países desde pequeño y haber crecido entre las culturas española y mexicana me ha dado una visión amplia que define cómo afronto las ideas y los retos. Estar rodeado de personas con trayectorias profesionales muy diversas también me ha expuesto, desde muy joven, a distintas formas de pensar y de resolver problemas.',
      'Más allá de lo académico, me mueve la idea de crear algo con sentido. Ya sea fundando un club de inversión centrado en la IA, colaborando con organizaciones benéficas o compitiendo en fútbol y karting, valoro la disciplina, la curiosidad y la mejora continua. Estas experiencias han reforzado mi convicción de contribuir a algo más grande que yo.',
      'De cara al futuro, mi ambición es sencilla: construir, innovar y dejar un impacto duradero.',
    ],
    sign: 'Atentamente,',
    toolkitTitle: 'Herramientas',
    toolkit: [
      { group: 'Ingeniería', items: ['Aerodinámica', 'Pensamiento ingenieril', 'Experimentación'] },
      { group: 'Empresa', items: ['Gestión empresarial', 'Análisis de inversiones', 'Gestión de proyectos'] },
      { group: 'Comunicación', items: ['Comunicación técnica', 'Entrevistas', 'Cinco idiomas'] },
    ],
  },
  features: {
    eyebrow: 'Lo que hago',
    title: 'Tres cosas',
    titleItalic: 'que me mueven.',
    sub: 'Aprender de las personas detrás de las máquinas, entender la física que las hace rápidas y compaginarlo todo con un grado de ingeniería.',
    podcast: {
      tag: 'Podcast',
      title: 'Inside The Machine',
      desc: 'Conversaciones en profundidad con pilotos, coleccionistas, diseñadores e ingenieros, en inglés y en español.',
      bullets: ['7 episodios y contando', 'Invitados como Enzo Fittipaldi', 'YouTube · Spotify · TikTok'],
    },
    aero: {
      tag: 'Aerodinámica',
      title: 'Investigación e ingeniería',
      desc: 'Mi trabajo de investigación del IB midió cómo la longitud del alerón trasero cambia la carga aerodinámica en un Porsche 911 RSR a escala.',
      bullets: ['Experimentos controlados', 'Física aplicada', 'Lee el trabajo completo'],
      header: 'Flujo de aire · alerón',
      states: ['Midiendo carga aerodinámica', 'Ajustando el alerón', 'Flujo adherido', 'Registrando resultados'],
    },
    now: {
      tag: 'Ahora mismo',
      title: 'Estudios + estudio',
      desc: 'Clases de ingeniería y empresa en la UFV entre semana y, entre medias, grabando y editando el próximo episodio.',
      bullets: ['Ingeniería + Minor en Empresa', 'Ep. 7 en producción', 'Invirtiendo por mi cuenta'],
      week: ['L', 'M', 'X', 'J', 'V', 'S', 'D'],
      lecture: 'Clases',
      record: 'Grabación',
      booked: 'Sesión del Ep. 7 reservada',
      picking: 'Planificando la semana…',
    },
  },
  pillars: {
    eyebrow: 'En cifras',
    items: [
      { label: 'Episodios del podcast', end: 7, suffix: '', desc: 'Del Episodio 0 en enero a la Monterey Car Week, con invitados de México, EE. UU. y más allá.' },
      { label: 'Idiomas', end: 5, suffix: '', desc: 'Criado entre las culturas española y mexicana, tras vivir en tres países desde pequeño.' },
      { label: 'Años de trabajo comunitario', end: 10, suffix: '+', desc: 'Clubes, organizaciones benéficas y fundaciones, incluida la presidencia del Global Citizens Club.' },
    ],
  },
  journey: {
    eyebrow: 'Mi trayectoria',
    title: 'Tres países,',
    titleItalic: 'una constante: aprender.',
    sub: 'Cuatro colegios entre México, España y Suiza: cada mudanza, un idioma nuevo, una cultura nueva y una forma nueva de ver las cosas.',
    stops: [
      {
        flag: '🇲🇽',
        place: 'Ciudad de México, México',
        chip: 'Ciudad de México',
        span: '8',
        unit: 'años',
        school: 'The American School Foundation',
        desc: 'Donde empezó todo. Ocho años creciendo entre las culturas española y mexicana: la raíz de la perspectiva que aporto a todo lo que hago.',
        photoDesc: 'Una foto de tus años en México: en el ASF, en Ciudad de México o una foto familiar antigua.',
      },
      {
        flag: '🇪🇸',
        place: 'Madrid, España',
        chip: 'Madrid',
        span: '6',
        unit: 'años',
        school: 'American School of Madrid',
        desc: 'Una ciudad nueva y un capítulo nuevo. Seis años en Madrid, construyendo amistades, rutinas y los intereses que todavía me mueven hoy.',
        photoDesc: 'Tú en Madrid o en el ASM durante esos años.',
      },
      {
        flag: '🇨🇭',
        place: 'Leysin, Suiza',
        chip: 'Leysin',
        span: '1',
        unit: 'año',
        school: 'Leysin American School',
        desc: 'Un año en un internado en los Alpes suizos: viviendo de forma independiente, rodeado de estudiantes de todo el mundo.',
        photoDesc: 'Tú en Leysin: el campus, las montañas o con compañeros.',
      },
      {
        flag: '🇪🇸',
        place: 'De vuelta en Madrid',
        chip: 'Madrid',
        span: 'IB',
        unit: 'Diploma',
        school: 'American School of Madrid',
        desc: 'Volví a Madrid y completé el Bachillerato Internacional con Física, Química y Gestión Empresarial de Nivel Superior, incluido mi trabajo de investigación en aerodinámica.',
        link: 'Lee el trabajo de investigación',
        photoDesc: 'Tu graduación del IB o el Porsche 911 RSR a escala de tu trabajo de investigación.',
      },
      {
        flag: '🎓',
        place: 'Madrid, España · Ahora',
        chip: 'UFV',
        span: 'UFV',
        unit: 'Ahora',
        now: true,
        school: 'Universidad Francisco de Vitoria',
        desc: 'Estudiando Ingeniería en Automoción e Industrial con un Minor en Administración de Empresas, mientras construyo Inside The Machine y gestiono mi propia cartera de inversión en paralelo.',
      },
    ],
  },
  projects: {
    eyebrow: 'Proyectos',
    title: 'Lo que estoy',
    titleItalic: 'construyendo.',
    sub: 'Proyectos reales que muestran mis intereses y lo que soy capaz de crear.',
    open: 'Abrir',
    items: [
      { key: 'podcast', title: 'Podcast Inside The Machine', desc: 'Cómo la ingeniería, el diseño y la aerodinámica definen el rendimiento y la identidad de los coches, de los de calle a los de competición, contado por las personas que viven el motor.', tags: ['Audio', 'Vídeo', 'Entrevistas'] },
      { key: 'paper', title: 'Trabajo de investigación en aerodinámica', desc: 'Mi Monografía del IB investigó con rigor el impacto de la longitud del alerón trasero en la carga aerodinámica de un Porsche 911 RSR a escala, uniendo teoría aerodinámica y experimentación controlada.', tags: ['Aerodinámica', 'Motor', 'Física aplicada'] },
      { key: 'club', title: 'Inversión', desc: 'Lo que empezó como un club de inversión centrado en la IA que fundé es hoy mi propia cartera a largo plazo: investigando empresas de distintos sectores y regiones, y aprendiendo de cada decisión.', tags: ['Inversión', 'Análisis', 'Estrategia'] },
      { key: 'services', title: 'Global Citizens Club y voluntariado', desc: 'Más de una década en clubes, iniciativas benéficas y fundaciones, incluida la presidencia del Global Citizens Club, conectando a los estudiantes con causas globales y con su comunidad local.', tags: ['Liderazgo', 'Voluntariado', 'Comunidad'] },
      { key: 'sport', title: 'Karting y fútbol', desc: 'Compitiendo en la pista y en el campo, donde la disciplina, la concentración y la mentalidad competitiva se ponen a prueba cada semana.', tags: ['Motor', 'Trabajo en equipo', 'Competición'] },
    ],
  },
  contact: {
    eyebrow: 'Contacto',
    title: 'Hablemos',
    titleItalic: 'un rato.',
    sub: 'Una idea, una colaboración, un invitado para el podcast… o simplemente para saludar.',
    emailLabel: 'Correo',
    linkedinLabel: 'LinkedIn',
    instagramLabel: 'Instagram',
    note: 'Al pulsar enviar se abrirá tu aplicación de correo con el mensaje listo.',
    name: 'Nombre',
    namePh: 'Tu nombre',
    email: 'Correo',
    emailPh: 'tu@correo.com',
    message: 'Mensaje',
    messagePh: '¿De qué te gustaría hablar?',
    send: 'Enviar mensaje',
    sending: 'Abriendo tu correo…',
    sentTitle: 'Casi listo.',
    sentDesc: 'Tu aplicación de correo debería haberse abierto con el mensaje preparado; solo tienes que enviarlo desde ahí.',
    again: 'Escribir otro mensaje',
    missing: 'Por favor, rellena todos los campos.',
  },
  footer: {
    tagline: 'Estudiante de Ingeniería en Automoción e Industrial y presentador de Inside The Machine.',
    status: 'Estudiando en la UFV · Madrid',
    explore: 'Explorar',
    club: 'Inversión',
    podcast: 'Podcast',
    connect: 'Conecta',
    rights: 'Todos los derechos reservados.',
    made: 'Siempre aprendiendo · Madrid',
  },
  podcastPage: {
    eyebrow: 'Podcast · Presentado por Jordi Facha Álvarez',
    line1: 'Inside',
    line2: 'The Machine.',
    sub: 'Exploramos cómo la ingeniería, el diseño y la aerodinámica definen el rendimiento y la identidad de los coches, de los de calle a los de competición, hablando con las personas que viven el mundo del motor.',
    watch: 'Ver en YouTube',
    listen: 'Escuchar en Spotify',
    chips: ['7 episodios', 'English & Español'],
    newChip: 'Nuevo: Ep. 6 — Monterey Car Week',
    aboutEyebrow: 'Sobre el programa',
    aboutTitle: 'Donde el motor',
    aboutTitleItalic: 'se encuentra con la ingeniería.',
    aboutP: [
      'Inside The Machine levanta el telón del motor y la cultura del automóvil. Cada episodio profundiza en la parte técnica: la aerodinámica, las decisiones de ingeniería y las filosofías de diseño que separan a los coches rápidos de los campeones.',
      'Más allá de las máquinas, el programa da voz a quienes lo viven: un tres veces ganador de La Carrera Panamericana, pilotos profesionales, coleccionistas de Ferrari, diseñadores de automóviles y mecánicos convertidos en pilotos.',
    ],
    stats: [
      { end: 7, suffix: '', label: 'Episodios publicados' },
      { end: 5, suffix: '', label: 'Invitados de dentro de la industria' },
      { end: 2, suffix: '', label: 'Idiomas: inglés y español' },
    ],
    latestEyebrow: 'Nuevo episodio',
    latestTitle: 'El último',
    latestTitleItalic: 'episodio.',
    episodeLabel: 'Episodio',
    watchYt: 'Ver en YouTube',
    listenSp: 'Escuchar en Spotify',
    archiveEyebrow: 'Todos los episodios',
    archiveTitle: 'El archivo',
    archiveTitleItalic: 'completo.',
    archiveSub: 'Los tres episodios más recientes: abre la lista completa para ver todas las conversaciones desde el Episodio 0.',
    showAll: 'Ver todos los episodios',
    hideAll: 'Ver menos episodios',
    followEyebrow: 'Encuéntranos en',
    followTitle: 'Escucha y',
    followTitleItalic: 'síguenos.',
    platforms: {
      youtube: 'Episodios completos y shorts',
      spotify: 'Inside The Machine Podcast',
      tiktok: 'Clips y momentos destacados',
      instagram: '@inside_the_machine_',
      email: 'Invitados y colaboraciones',
    },
    playTitle: 'Dale al',
    playTitleItalic: 'play.',
    mosaicLabel: 'Últimos episodios',
  },
  clubPage: {
    eyebrow: 'Inversión',
    line1: 'Invirtiendo en',
    line2: 'el futuro.',
    sub: 'Invierto a largo plazo. Empezó como un club de inversión centrado en la IA que fundé; hoy gestiono mi propia cartera: diversificada por sectores y regiones, y basada en entender cada empresa en la que invierto.',
    allocEyebrow: 'Distribución de la cartera',
    allocTitle: 'Desglose',
    allocTitleItalic: 'actual.',
    total: 'Total',
    categories: {
      growth: 'Crecimiento / Especulativo',
      value: 'Valor / Dividendos',
      etf: 'ETF',
      tech: 'Tecnológicas de gran capitalización',
    },
    disclaimer: 'Estas son algunas de las empresas de mi cartera, elegidas para mostrar su diversidad por sectores y regiones. No son necesariamente mis posiciones más rentables ni las de mayor peso: simplemente una muestra del abanico de oportunidades en las que he invertido.',
    notable: 'Posiciones destacadas',
    viewAll: 'Ver la cartera completa',
    hideAll: 'Ocultar la cartera completa',
  },
  servicesPage: {
    eyebrow: 'Global Citizens Club y voluntariado',
    line1: 'Construyendo cosas',
    line2: 'que importan.',
    sub: 'Más de una década participando en clubes, iniciativas benéficas y fundaciones, incluida la presidencia del Global Citizens Club. Esta página recogerá ese trabajo.',
    soonTag: 'Próximamente',
    soonTitle: 'Esta página está en construcción.',
    soonDesc: 'Vuelve pronto para conocer el trabajo benéfico, las iniciativas y los proyectos comunitarios en los que he participado.',
    back: 'Volver al portfolio',
    photos: [
      { title: 'Global Citizens Club', desc: 'Tú liderando una reunión o un evento del club, hablando o con el equipo a tu alrededor. Horizontal 4:3.' },
      { title: 'Voluntariado', desc: 'Tú colaborando en una de las organizaciones o fundaciones: en acción, natural y con caras visibles. Horizontal 4:3.' },
    ],
  },
}

export const COPY = { en, es }
