// All site copy, English + Spanish. Keep both objects in the same shape.

const en = {
  meta: {
    title: 'Jordi Facha Álvarez — Engineering Student & Podcaster',
    podcastTitle: 'Inside The Machine — Jordi Facha Álvarez',
    clubTitle: 'AI Investment Club — Jordi Facha Álvarez',
    servicesTitle: 'Services & Community — Jordi Facha Álvarez',
  },
  nav: {
    about: 'About',
    journey: 'Journey',
    projects: 'Projects',
    podcast: 'Podcast',
    contact: 'Contact',
    cta: 'Get in touch',
    menu: 'Open menu',
    close: 'Close menu',
    back: 'Back to portfolio',
  },
  photo: {
    label: 'Photo to add',
  },
  hero: {
    eyebrow: 'Automotive & Industrial Engineering · UFV Madrid',
    line1: 'Hi, I’m Jordi.',
    line2: 'Engineering what moves.',
    sub: 'Engineering student at Universidad Francisco de Vitoria and host of Inside The Machine — a podcast on the engineering, design and people behind motorsport.',
    ctaPrimary: 'Watch the podcast',
    ctaSecondary: 'LinkedIn',
    live: 'New',
    scroll: 'Scroll',
    photoTitle: 'Hero portrait',
    photoDesc: 'You in a race suit or casual jacket next to a car or kart, shot from a slightly low angle at golden hour. Vertical 4:5, with you on one side and some empty space around you.',
  },
  about: {
    eyebrow: 'About me',
    title: 'Curious by nature,',
    titleItalic: 'creative by choice.',
    p: [
      'Curiosity has always been the driving force behind everything I do, an ongoing desire to learn, explore, and understand how things work. That mindset has shaped my path into studying Automotive and Industrial Engineering at Universidad Francisco de Vitoria in Madrid, as well as pursuing challenges beyond the classroom. From completing the IB Diploma with Higher Level Physics and Chemistry to learning five languages and launching a motorsport podcast where I speak with people inside the industry, I’ve consistently sought out opportunities to expand my perspective.',
      'Having lived in three countries early in life and grown up between Spanish and Mexican cultures, I’ve developed a broad perspective that shapes how I approach ideas and challenges. Being surrounded by people from a wide range of professional backgrounds has also exposed me to different ways of thinking and problem-solving from an early age.',
      'Beyond academics, I’m driven by the idea of creating something meaningful. Whether it’s founding an AI-focused investment club, working alongside charities, or competing in football and karting, I value discipline, curiosity, and continuous improvement. These experiences have reinforced my belief in contributing to something larger than myself.',
      'Looking ahead, my ambition is simple: to build, to innovate, and to leave a lasting impact.',
    ],
    sign: 'Sincerely,',
  },
  features: {
    eyebrow: 'What I do',
    title: 'Three things',
    titleItalic: 'that drive me.',
    sub: 'Talking to the people behind the machines, understanding the physics that makes them fast, and fitting it all around an engineering degree.',
    podcast: {
      tag: 'Podcast',
      title: 'Inside The Machine',
      desc: 'Long-form conversations with drivers, collectors, designers and engineers — in English and Spanish.',
      bullets: ['7 episodes and counting', 'Guests incl. Enzo Fittipaldi', 'YouTube · Spotify · TikTok'],
    },
    aero: {
      tag: 'Aerodynamics',
      title: 'Research & engineering',
      desc: 'My IB research paper measured how rear wing length changes downforce on a model Porsche 911 RSR.',
      bullets: ['Controlled experiments', 'Applied physics', 'Read the full paper'],
      header: 'Airflow · rear wing',
      states: ['Measuring downforce', 'Adjusting wing length', 'Flow attached', 'Logging results'],
    },
    now: {
      tag: 'Right now',
      title: 'Studies + studio',
      desc: 'Engineering lectures at UFV during the week, recording and editing the next episode in between.',
      bullets: ['Year at UFV Madrid', 'Ep. 7 in production', 'AI Investment Club'],
      week: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
      lecture: 'Lectures',
      record: 'Recording',
      booked: 'Ep. 7 session booked',
      picking: 'Planning the week…',
    },
  },
  pillars: {
    eyebrow: 'By the numbers',
    items: [
      { label: 'Podcast episodes', end: 7, suffix: '', desc: 'From Episode 0 in January to Monterey Car Week — with guests from Mexico, the US and beyond.' },
      { label: 'Languages', end: 5, suffix: '', desc: 'Grown up between Spanish and Mexican cultures, having lived in three countries early in life.' },
      { label: 'Years of community work', end: 10, suffix: '+', desc: 'Clubs, charities and foundations — including serving as President of the Global Citizens Club.' },
    ],
  },
  journey: {
    eyebrow: 'My journey',
    title: 'From curiosity',
    titleItalic: 'to engineering.',
    steps: [
      {
        tag: 'Foundation',
        title: 'IB Diploma',
        desc: 'Completed the International Baccalaureate with Higher Level Physics and Chemistry. My Extended Essay put theory into a wind-tunnel-style experiment: how rear wing length affects downforce on a model Porsche 911 RSR.',
        bullets: ['HL Physics & HL Chemistry', 'Aerodynamics research paper', 'Five languages'],
        link: 'Read the research paper',
        photoTitle: 'Research setup',
        photoDesc: 'The model Porsche 911 RSR and your experiment setup (fan, scale, wing pieces), or you working on it. Horizontal 4:3, close-up and well lit.',
      },
      {
        tag: 'Now',
        title: 'Automotive & Industrial Engineering',
        desc: 'Studying at Universidad Francisco de Vitoria in Madrid — turning a lifelong curiosity for how cars work into an engineering career, from vehicle mechanics and design to industrial systems and manufacturing.',
        bullets: ['Universidad Francisco de Vitoria', 'Madrid, Spain', 'Vehicle & industrial engineering'],
        photoTitle: 'At UFV',
        photoDesc: 'You on the UFV campus or in a lab or workshop — ideally with the university sign or building visible. Horizontal 4:3, natural daylight.',
      },
      {
        tag: 'Beyond the classroom',
        title: 'Building things that matter',
        desc: 'Hosting Inside The Machine, founding an AI-focused investment club, leading the Global Citizens Club and over a decade of charity work — plus football and karting to keep the competitive edge.',
        bullets: ['Podcast host & producer', 'Founder, AI Investment Club', 'President, Global Citizens Club'],
        photoTitle: 'Behind the mic',
        photoDesc: 'You recording an episode: microphone and headphones in frame, ideally with a guest blurred in the background. Horizontal 4:3, moody studio lighting.',
      },
    ],
  },
  projects: {
    eyebrow: 'Projects',
    title: 'What I’m',
    titleItalic: 'building.',
    sub: 'Real projects that show my interests and what I’m capable of creating.',
    open: 'Open',
    items: [
      { key: 'podcast', title: 'Inside The Machine Podcast', desc: 'How engineering, design and aerodynamics shape the performance and identity of cars — from road vehicles to race machines — told through the people inside motorsport.', tags: ['Audio', 'Video', 'Interviews'] },
      { key: 'paper', title: 'Aerodynamics Research Paper', desc: 'My IB Extended Essay rigorously investigated the impact of rear wing length on downforce in a model Porsche 911 RSR, combining aerodynamic theory with controlled experimentation.', tags: ['Aerodynamics', 'Motorsport', 'Applied Physics'] },
      { key: 'club', title: 'AI Investment Club', desc: 'Collaborative investment learning: sharing insights and strategies, simplifying markets and helping new investors make confident, informed long-term decisions.', tags: ['Investing', 'Analysis', 'Strategy'] },
      { key: 'services', title: 'Services & Charity', desc: 'Over a decade of involvement in clubs, charitable initiatives and foundations — work I’m proud to share.', tags: ['Charity', 'Impact', 'Community'] },
      { key: 'gcc', title: 'Global Citizens Club', desc: 'Served as President, leading initiatives that connect students with global causes and their local community.', tags: ['Leadership', 'Initiative'] },
      { key: 'sport', title: 'Karting & Football', desc: 'Competing on track and on the pitch — where discipline, focus and a competitive mindset get tested every week.', tags: ['Motorsport', 'Teamwork', 'Competition'] },
    ],
  },
  highlights: {
    eyebrow: 'Highlights',
    title: 'Proof of',
    titleItalic: 'curiosity.',
    items: [
      { title: 'Conversations at the top', desc: 'Interviewed racing driver Enzo Fittipaldi and three-time Carrera Panamericana winner Diego Cándano.' },
      { title: 'IB Diploma', desc: 'Higher Level Physics and Chemistry, with an original aerodynamics research paper.' },
      { title: 'Leadership', desc: 'President of the Global Citizens Club and founder of an AI-focused investment club.' },
    ],
    skillsTitle: 'Toolkit',
    skills: [
      { group: 'Engineering', items: ['Aerodynamics', 'Engineering thinking', 'Experimentation'] },
      { group: 'Communication', items: ['Technical communication', 'Interviewing', 'Five languages'] },
      { group: 'Leadership', items: ['Project management', 'Community building', 'Investment analysis'] },
    ],
  },
  contact: {
    eyebrow: 'Contact',
    title: 'Let’s',
    titleItalic: 'talk.',
    sub: 'An idea, a collaboration, a guest suggestion for the podcast — or just to say hi.',
    emailLabel: 'Email',
    linkedinLabel: 'LinkedIn',
    instagramLabel: 'Instagram',
    note: 'Pressing send opens your email app with the message ready to go.',
    name: 'Name',
    namePh: 'Your name',
    email: 'Email',
    emailPh: 'you@email.com',
    message: 'Message',
    messagePh: 'What would you like to talk about?',
    send: 'Send message',
    sending: 'Opening your email…',
    sentTitle: 'Almost there.',
    sentDesc: 'Your email app should have opened with the message ready — just hit send there.',
    again: 'Write another message',
    missing: 'Please fill in all fields.',
  },
  footer: {
    tagline: 'Automotive & Industrial Engineering student and host of Inside The Machine.',
    status: 'Currently studying at UFV · Madrid',
    explore: 'Explore',
    club: 'AI Investment Club',
    podcast: 'Podcast',
    connect: 'Connect',
    rights: 'All rights reserved.',
    made: 'Built with curiosity in Madrid.',
  },
  podcastPage: {
    eyebrow: 'Podcast · Hosted by Jordi Facha Álvarez',
    line1: 'Inside',
    line2: 'The Machine.',
    sub: 'Exploring how engineering, design and aerodynamics shape the performance and identity of cars — from road vehicles to race machines — while speaking with the people inside the motorsport world.',
    watch: 'Watch on YouTube',
    listen: 'Listen on Spotify',
    chips: ['7 episodes', 'English & Español'],
    newChip: 'New: Ep. 6 — Monterey Car Week',
    aboutEyebrow: 'About the show',
    aboutTitle: 'Where motorsport',
    aboutTitleItalic: 'meets engineering.',
    aboutP: [
      'Inside The Machine pulls back the curtain on motorsport and car culture. Every episode digs into the technical side — the aerodynamics, the engineering decisions and the design philosophies that separate fast cars from championship-winning ones.',
      'Beyond the machines, the show features the people who live it: a three-time Carrera Panamericana winner, professional racing drivers, Ferrari collectors, automotive designers and mechanics-turned-racers.',
    ],
    stats: [
      { end: 7, suffix: '', label: 'Episodes released' },
      { end: 5, suffix: '', label: 'Guests from inside the industry' },
      { end: 2, suffix: '', label: 'Languages — English & Español' },
    ],
    latestEyebrow: 'New episode',
    latestTitle: 'The latest',
    latestTitleItalic: 'episode.',
    episodeLabel: 'Episode',
    watchYt: 'Watch on YouTube',
    listenSp: 'Listen on Spotify',
    archiveEyebrow: 'Every episode',
    archiveTitle: 'The full',
    archiveTitleItalic: 'archive.',
    archiveSub: 'From the very first episode to the latest — every conversation, newest first.',
    followEyebrow: 'Find us on',
    followTitle: 'Listen &',
    followTitleItalic: 'follow.',
    platforms: {
      youtube: 'Full episodes & shorts',
      spotify: 'Inside The Machine Podcast',
      tiktok: 'Clips & highlights',
      instagram: '@inside_the_machine_podcast',
      email: 'Guest & partnership enquiries',
    },
    playTitle: 'Press',
    playTitleItalic: 'play.',
    photoTitle: 'Podcast studio',
    photoDesc: 'A wide shot of the recording setup — two mics, headphones, the Inside The Machine logo or a car in the background. Horizontal 16:9, cinematic and slightly dark.',
  },
  clubPage: {
    eyebrow: 'AI Investment Club',
    line1: 'Investing in',
    line2: 'the future.',
    sub: 'We foster collaborative investment learning, sharing insights and strategies while educating new investors. Focused on long-term growth, we simplify markets, build financial understanding, and empower confident, informed decisions for sustainable wealth.',
    allocEyebrow: 'Portfolio allocation',
    allocTitle: 'Current',
    allocTitleItalic: 'breakdown.',
    total: 'Total',
    categories: {
      growth: 'Growth / Speculative',
      value: 'Value / Dividends',
      etf: 'ETFs',
      tech: 'Large Cap Tech',
    },
    disclaimer: 'The following are some of the companies in my portfolio, selected to illustrate its diversity across sectors and geographies. They are not necessarily my highest-yielding positions or largest holdings by weight — simply a snapshot of the range of opportunities I’ve invested in.',
    notable: 'Notable holdings',
    viewAll: 'View full portfolio',
    hideAll: 'Hide full portfolio',
  },
  servicesPage: {
    eyebrow: 'Services & Community Work',
    line1: 'Building things',
    line2: 'that matter.',
    sub: 'Over a decade of involvement in clubs, charitable initiatives and foundations, including serving as President of the Global Citizens Club. This page will showcase that work.',
    soonTag: 'Coming soon',
    soonTitle: 'This page is being built.',
    soonDesc: 'Check back soon to learn more about the charitable work, initiatives and community projects I’ve been part of.',
    back: 'Back to portfolio',
    photos: [
      { title: 'Global Citizens Club', desc: 'You leading a club meeting or event — speaking, or with the team around you. Horizontal 4:3.' },
      { title: 'Charity work', desc: 'You volunteering at one of the charities or foundations — hands-on, candid, faces visible. Horizontal 4:3.' },
    ],
  },
}

const es = {
  meta: {
    title: 'Jordi Facha Álvarez — Estudiante de Ingeniería y Podcaster',
    podcastTitle: 'Inside The Machine — Jordi Facha Álvarez',
    clubTitle: 'Club de Inversión IA — Jordi Facha Álvarez',
    servicesTitle: 'Servicios y Comunidad — Jordi Facha Álvarez',
  },
  nav: {
    about: 'Sobre mí',
    journey: 'Trayectoria',
    projects: 'Proyectos',
    podcast: 'Podcast',
    contact: 'Contacto',
    cta: 'Contáctame',
    menu: 'Abrir menú',
    close: 'Cerrar menú',
    back: 'Volver al portfolio',
  },
  photo: {
    label: 'Foto pendiente',
  },
  hero: {
    eyebrow: 'Ingeniería en Automoción e Industrial · UFV Madrid',
    line1: 'Hola, soy Jordi.',
    line2: 'Ingeniería en movimiento.',
    sub: 'Estudiante de ingeniería en la Universidad Francisco de Vitoria y presentador de Inside The Machine, un podcast sobre la ingeniería, el diseño y las personas detrás del motor.',
    ctaPrimary: 'Ver el podcast',
    ctaSecondary: 'LinkedIn',
    live: 'Nuevo',
    scroll: 'Desliza',
    photoTitle: 'Retrato principal',
    photoDesc: 'Tú con mono de carreras o chaqueta informal junto a un coche o kart, desde un ángulo ligeramente bajo y con luz de atardecer. Vertical 4:5, contigo a un lado y algo de espacio libre alrededor.',
  },
  about: {
    eyebrow: 'Sobre mí',
    title: 'Curioso por naturaleza,',
    titleItalic: 'creativo por elección.',
    p: [
      'La curiosidad siempre ha sido el motor de todo lo que hago: un deseo constante de aprender, explorar y entender cómo funcionan las cosas. Esa mentalidad me ha llevado a estudiar Ingeniería en Automoción e Industrial en la Universidad Francisco de Vitoria, en Madrid, y a buscar retos más allá de las aulas. Desde completar el Bachillerato Internacional con Física y Química de Nivel Superior hasta aprender cinco idiomas y lanzar un podcast de motor en el que hablo con personas de dentro de la industria, siempre he buscado oportunidades para ampliar mi perspectiva.',
      'Haber vivido en tres países desde pequeño y haber crecido entre las culturas española y mexicana me ha dado una visión amplia que define cómo afronto las ideas y los retos. Estar rodeado de personas con trayectorias profesionales muy diversas también me ha expuesto, desde muy joven, a distintas formas de pensar y de resolver problemas.',
      'Más allá de lo académico, me mueve la idea de crear algo con sentido. Ya sea fundando un club de inversión centrado en la IA, colaborando con organizaciones benéficas o compitiendo en fútbol y karting, valoro la disciplina, la curiosidad y la mejora continua. Estas experiencias han reforzado mi convicción de contribuir a algo más grande que yo.',
      'De cara al futuro, mi ambición es sencilla: construir, innovar y dejar un impacto duradero.',
    ],
    sign: 'Atentamente,',
  },
  features: {
    eyebrow: 'Lo que hago',
    title: 'Tres cosas',
    titleItalic: 'que me mueven.',
    sub: 'Hablar con las personas detrás de las máquinas, entender la física que las hace rápidas y compaginarlo todo con un grado de ingeniería.',
    podcast: {
      tag: 'Podcast',
      title: 'Inside The Machine',
      desc: 'Conversaciones en profundidad con pilotos, coleccionistas, diseñadores e ingenieros, en inglés y en español.',
      bullets: ['7 episodios y contando', 'Invitados como Enzo Fittipaldi', 'YouTube · Spotify · TikTok'],
    },
    aero: {
      tag: 'Aerodinámica',
      title: 'Investigación e ingeniería',
      desc: 'Mi trabajo de investigación del IB midió cómo la longitud del alerón trasero cambia la carga aerodinámica en un Porsche 911 RSR a escala.',
      bullets: ['Experimentos controlados', 'Física aplicada', 'Lee el trabajo completo'],
      header: 'Flujo de aire · alerón',
      states: ['Midiendo carga aerodinámica', 'Ajustando el alerón', 'Flujo adherido', 'Registrando resultados'],
    },
    now: {
      tag: 'Ahora mismo',
      title: 'Estudios + estudio',
      desc: 'Clases de ingeniería en la UFV entre semana y, entre medias, grabando y editando el próximo episodio.',
      bullets: ['Curso en la UFV Madrid', 'Ep. 7 en producción', 'Club de Inversión IA'],
      week: ['L', 'M', 'X', 'J', 'V', 'S', 'D'],
      lecture: 'Clases',
      record: 'Grabación',
      booked: 'Sesión del Ep. 7 reservada',
      picking: 'Planificando la semana…',
    },
  },
  pillars: {
    eyebrow: 'En cifras',
    items: [
      { label: 'Episodios del podcast', end: 7, suffix: '', desc: 'Del Episodio 0 en enero a la Monterey Car Week, con invitados de México, EE. UU. y más allá.' },
      { label: 'Idiomas', end: 5, suffix: '', desc: 'Criado entre las culturas española y mexicana, tras vivir en tres países desde pequeño.' },
      { label: 'Años de trabajo comunitario', end: 10, suffix: '+', desc: 'Clubes, organizaciones benéficas y fundaciones, incluida la presidencia del Global Citizens Club.' },
    ],
  },
  journey: {
    eyebrow: 'Mi trayectoria',
    title: 'De la curiosidad',
    titleItalic: 'a la ingeniería.',
    steps: [
      {
        tag: 'Base',
        title: 'Bachillerato Internacional',
        desc: 'Completé el Bachillerato Internacional con Física y Química de Nivel Superior. Mi Monografía llevó la teoría a un experimento tipo túnel de viento: cómo la longitud del alerón trasero afecta a la carga aerodinámica de un Porsche 911 RSR a escala.',
        bullets: ['Física y Química NS', 'Trabajo de investigación en aerodinámica', 'Cinco idiomas'],
        link: 'Lee el trabajo de investigación',
        photoTitle: 'Montaje del experimento',
        photoDesc: 'El Porsche 911 RSR a escala y el montaje del experimento (ventilador, báscula, piezas del alerón), o tú trabajando en él. Horizontal 4:3, en primer plano y bien iluminado.',
      },
      {
        tag: 'Ahora',
        title: 'Ingeniería en Automoción e Industrial',
        desc: 'Estudiando en la Universidad Francisco de Vitoria, en Madrid: convirtiendo mi curiosidad de siempre por cómo funcionan los coches en una carrera de ingeniería, desde la mecánica y el diseño de vehículos hasta los sistemas industriales y la fabricación.',
        bullets: ['Universidad Francisco de Vitoria', 'Madrid, España', 'Ingeniería del vehículo e industrial'],
        photoTitle: 'En la UFV',
        photoDesc: 'Tú en el campus de la UFV o en un laboratorio o taller, idealmente con el letrero o el edificio de la universidad a la vista. Horizontal 4:3, con luz natural.',
      },
      {
        tag: 'Fuera del aula',
        title: 'Construyendo cosas que importan',
        desc: 'Presentando Inside The Machine, fundando un club de inversión centrado en la IA, liderando el Global Citizens Club y más de una década de trabajo benéfico, además de fútbol y karting para mantener el espíritu competitivo.',
        bullets: ['Presentador y productor del podcast', 'Fundador, Club de Inversión IA', 'Presidente, Global Citizens Club'],
        photoTitle: 'Detrás del micro',
        photoDesc: 'Tú grabando un episodio: micrófono y auriculares en el encuadre, idealmente con un invitado desenfocado al fondo. Horizontal 4:3, con iluminación de estudio tenue.',
      },
    ],
  },
  projects: {
    eyebrow: 'Proyectos',
    title: 'Lo que estoy',
    titleItalic: 'construyendo.',
    sub: 'Proyectos reales que muestran mis intereses y lo que soy capaz de crear.',
    open: 'Abrir',
    items: [
      { key: 'podcast', title: 'Podcast Inside The Machine', desc: 'Cómo la ingeniería, el diseño y la aerodinámica definen el rendimiento y la identidad de los coches, de los de calle a los de competición, contado por las personas que viven el motor.', tags: ['Audio', 'Vídeo', 'Entrevistas'] },
      { key: 'paper', title: 'Trabajo de investigación en aerodinámica', desc: 'Mi Monografía del IB investigó con rigor el impacto de la longitud del alerón trasero en la carga aerodinámica de un Porsche 911 RSR a escala, uniendo teoría aerodinámica y experimentación controlada.', tags: ['Aerodinámica', 'Motor', 'Física aplicada'] },
      { key: 'club', title: 'Club de Inversión IA', desc: 'Aprendizaje colaborativo de inversión: compartir ideas y estrategias, simplificar los mercados y ayudar a nuevos inversores a tomar decisiones informadas y con visión a largo plazo.', tags: ['Inversión', 'Análisis', 'Estrategia'] },
      { key: 'services', title: 'Servicios y voluntariado', desc: 'Más de una década participando en clubes, iniciativas benéficas y fundaciones; un trabajo del que me siento orgulloso.', tags: ['Voluntariado', 'Impacto', 'Comunidad'] },
      { key: 'gcc', title: 'Global Citizens Club', desc: 'Fui presidente, liderando iniciativas que conectan a los estudiantes con causas globales y con su comunidad local.', tags: ['Liderazgo', 'Iniciativa'] },
      { key: 'sport', title: 'Karting y fútbol', desc: 'Compitiendo en la pista y en el campo, donde la disciplina, la concentración y la mentalidad competitiva se ponen a prueba cada semana.', tags: ['Motor', 'Trabajo en equipo', 'Competición'] },
    ],
  },
  highlights: {
    eyebrow: 'Destacados',
    title: 'Pruebas de',
    titleItalic: 'curiosidad.',
    items: [
      { title: 'Conversaciones al más alto nivel', desc: 'He entrevistado al piloto Enzo Fittipaldi y a Diego Cándano, tres veces ganador de La Carrera Panamericana.' },
      { title: 'Bachillerato Internacional', desc: 'Física y Química de Nivel Superior, con un trabajo original de investigación en aerodinámica.' },
      { title: 'Liderazgo', desc: 'Presidente del Global Citizens Club y fundador de un club de inversión centrado en la IA.' },
    ],
    skillsTitle: 'Herramientas',
    skills: [
      { group: 'Ingeniería', items: ['Aerodinámica', 'Pensamiento ingenieril', 'Experimentación'] },
      { group: 'Comunicación', items: ['Comunicación técnica', 'Entrevistas', 'Cinco idiomas'] },
      { group: 'Liderazgo', items: ['Gestión de proyectos', 'Creación de comunidad', 'Análisis de inversiones'] },
    ],
  },
  contact: {
    eyebrow: 'Contacto',
    title: 'Hablemos',
    titleItalic: 'un rato.',
    sub: 'Una idea, una colaboración, un invitado para el podcast… o simplemente para saludar.',
    emailLabel: 'Correo',
    linkedinLabel: 'LinkedIn',
    instagramLabel: 'Instagram',
    note: 'Al pulsar enviar se abrirá tu aplicación de correo con el mensaje listo.',
    name: 'Nombre',
    namePh: 'Tu nombre',
    email: 'Correo',
    emailPh: 'tu@correo.com',
    message: 'Mensaje',
    messagePh: '¿De qué te gustaría hablar?',
    send: 'Enviar mensaje',
    sending: 'Abriendo tu correo…',
    sentTitle: 'Casi listo.',
    sentDesc: 'Tu aplicación de correo debería haberse abierto con el mensaje preparado; solo tienes que enviarlo desde ahí.',
    again: 'Escribir otro mensaje',
    missing: 'Por favor, rellena todos los campos.',
  },
  footer: {
    tagline: 'Estudiante de Ingeniería en Automoción e Industrial y presentador de Inside The Machine.',
    status: 'Estudiando en la UFV · Madrid',
    explore: 'Explorar',
    club: 'Club de Inversión IA',
    podcast: 'Podcast',
    connect: 'Conecta',
    rights: 'Todos los derechos reservados.',
    made: 'Hecho con curiosidad en Madrid.',
  },
  podcastPage: {
    eyebrow: 'Podcast · Presentado por Jordi Facha Álvarez',
    line1: 'Inside',
    line2: 'The Machine.',
    sub: 'Exploramos cómo la ingeniería, el diseño y la aerodinámica definen el rendimiento y la identidad de los coches, de los de calle a los de competición, hablando con las personas que viven el mundo del motor.',
    watch: 'Ver en YouTube',
    listen: 'Escuchar en Spotify',
    chips: ['7 episodios', 'English & Español'],
    newChip: 'Nuevo: Ep. 6 — Monterey Car Week',
    aboutEyebrow: 'Sobre el programa',
    aboutTitle: 'Donde el motor',
    aboutTitleItalic: 'se encuentra con la ingeniería.',
    aboutP: [
      'Inside The Machine levanta el telón del motor y la cultura del automóvil. Cada episodio profundiza en la parte técnica: la aerodinámica, las decisiones de ingeniería y las filosofías de diseño que separan a los coches rápidos de los campeones.',
      'Más allá de las máquinas, el programa da voz a quienes lo viven: un tres veces ganador de La Carrera Panamericana, pilotos profesionales, coleccionistas de Ferrari, diseñadores de automóviles y mecánicos convertidos en pilotos.',
    ],
    stats: [
      { end: 7, suffix: '', label: 'Episodios publicados' },
      { end: 5, suffix: '', label: 'Invitados de dentro de la industria' },
      { end: 2, suffix: '', label: 'Idiomas: inglés y español' },
    ],
    latestEyebrow: 'Nuevo episodio',
    latestTitle: 'El último',
    latestTitleItalic: 'episodio.',
    episodeLabel: 'Episodio',
    watchYt: 'Ver en YouTube',
    listenSp: 'Escuchar en Spotify',
    archiveEyebrow: 'Todos los episodios',
    archiveTitle: 'El archivo',
    archiveTitleItalic: 'completo.',
    archiveSub: 'Desde el primer episodio hasta el último: todas las conversaciones, de la más reciente a la más antigua.',
    followEyebrow: 'Encuéntranos en',
    followTitle: 'Escucha y',
    followTitleItalic: 'síguenos.',
    platforms: {
      youtube: 'Episodios completos y shorts',
      spotify: 'Inside The Machine Podcast',
      tiktok: 'Clips y momentos destacados',
      instagram: '@inside_the_machine_podcast',
      email: 'Invitados y colaboraciones',
    },
    playTitle: 'Dale al',
    playTitleItalic: 'play.',
    photoTitle: 'Estudio del podcast',
    photoDesc: 'Un plano general del set de grabación: dos micrófonos, auriculares y el logo de Inside The Machine o un coche al fondo. Horizontal 16:9, cinematográfico y algo oscuro.',
  },
  clubPage: {
    eyebrow: 'Club de Inversión IA',
    line1: 'Invirtiendo en',
    line2: 'el futuro.',
    sub: 'Fomentamos el aprendizaje colaborativo de inversión, compartiendo ideas y estrategias mientras formamos a nuevos inversores. Con la vista puesta en el crecimiento a largo plazo, simplificamos los mercados, construimos cultura financiera e impulsamos decisiones seguras e informadas para crear patrimonio sostenible.',
    allocEyebrow: 'Distribución de la cartera',
    allocTitle: 'Desglose',
    allocTitleItalic: 'actual.',
    total: 'Total',
    categories: {
      growth: 'Crecimiento / Especulativo',
      value: 'Valor / Dividendos',
      etf: 'ETF',
      tech: 'Tecnológicas de gran capitalización',
    },
    disclaimer: 'Estas son algunas de las empresas de mi cartera, elegidas para mostrar su diversidad por sectores y regiones. No son necesariamente mis posiciones más rentables ni las de mayor peso: simplemente una muestra del abanico de oportunidades en las que he invertido.',
    notable: 'Posiciones destacadas',
    viewAll: 'Ver la cartera completa',
    hideAll: 'Ocultar la cartera completa',
  },
  servicesPage: {
    eyebrow: 'Servicios y trabajo comunitario',
    line1: 'Construyendo cosas',
    line2: 'que importan.',
    sub: 'Más de una década participando en clubes, iniciativas benéficas y fundaciones, incluida la presidencia del Global Citizens Club. Esta página recogerá ese trabajo.',
    soonTag: 'Próximamente',
    soonTitle: 'Esta página está en construcción.',
    soonDesc: 'Vuelve pronto para conocer el trabajo benéfico, las iniciativas y los proyectos comunitarios en los que he participado.',
    back: 'Volver al portfolio',
    photos: [
      { title: 'Global Citizens Club', desc: 'Tú liderando una reunión o un evento del club, hablando o con el equipo a tu alrededor. Horizontal 4:3.' },
      { title: 'Voluntariado', desc: 'Tú colaborando en una de las organizaciones o fundaciones: en acción, natural y con caras visibles. Horizontal 4:3.' },
    ],
  },
}

export const COPY = { en, es }
