// All site copy, English + Spanish. Keep both objects in the same shape.

const en = {
  meta: {
    title: 'Jordi Facha Álvarez — Engineering Student & Podcaster',
    podcastTitle: 'Inside The Machine — Jordi Facha Álvarez',
    servicesTitle: 'Services & Community — Jordi Facha Álvarez',
    researchTitle: 'Research — Jordi Facha Álvarez',
  },
  nav: {
    about: 'About',
    journey: 'Journey',
    projects: 'Projects',
    podcast: 'Podcast',
    contact: 'Contact',
    cta: 'Get in touch',
    menu: 'Open menu',
    close: 'Close menu',
    back: 'Back to portfolio',
    allProjects: 'All projects',
    menuPodcast: 'Inside The Machine',
    menuPodcastDesc: 'Motorsport & engineering podcast',
    menuPaper: 'Research',
    menuPaperDesc: 'Aerodynamics papers',
    research: 'Research',
    menuCommunity: 'Community & charity',
    menuCommunityDesc: 'Global Citizens Club & more',
    themeLight: 'Switch to light mode',
    themeDark: 'Switch to dark mode',
  },
  photo: {
    label: 'Photo to add',
  },
  hero: {
    eyebrow: 'Engineering + Business · UFV Madrid',
    line1: 'Hi, I’m Jordi.',
    line2: 'Engineering what moves.',
    sub: 'Automotive & Industrial Engineering student with a Minor in Business Management at Universidad Francisco de Vitoria, part of the aerodynamics department of Formula Student UFV — and host of Inside The Machine, a podcast on the engineering, design and people behind motorsport.',
    ctaPrimary: 'Watch the podcast',
    ctaSecondary: 'LinkedIn',
    live: 'New',
    scroll: 'Scroll',
    photoTitle: 'Hero portrait',
    photoDesc: 'You in a race suit or casual jacket next to a car or kart, shot from a slightly low angle at golden hour. Vertical 4:5, with you on one side and some empty space around you.',
  },
  about: {
    eyebrow: 'About me',
    title: 'Always learning —',
    titleItalic: 'anything and everything.',
    p: [
      'Learning has always been the driving force behind everything I do — I love learning anything and everything I can, about any subject, and understanding how things really work. That mindset has shaped my path into studying Automotive and Industrial Engineering, with a Minor in Business Management, at Universidad Francisco de Vitoria in Madrid — where I’m also part of the aerodynamics department of Formula Student UFV — as well as pursuing challenges beyond the classroom. From completing the IB Diploma with Higher Level Physics, Chemistry and Business Management to learning five languages and launching a motorsport podcast where I speak with people inside the industry, I’ve consistently sought out opportunities to keep learning.',
      'Having lived in three countries early in life and grown up between Spanish and Mexican cultures, I’ve developed a broad perspective that shapes how I approach ideas and challenges. Being surrounded by people from a wide range of professional backgrounds has also exposed me to different ways of thinking and problem-solving from an early age.',
      'Beyond academics, I’m driven by the idea of creating something meaningful. Whether it’s founding an AI-focused investment club, working alongside charities, or competing in football and karting, I value discipline, curiosity, and continuous improvement. These experiences have reinforced my belief in contributing to something larger than myself.',
      'Looking ahead, my ambition is simple: to build, to innovate, and to leave a lasting impact.',
    ],
    sign: 'Sincerely,',
    toolkitTitle: 'Toolkit',
    toolkit: [
      { group: 'Engineering', items: ['Aerodynamics', 'Engineering thinking', 'Experimentation'] },
      { group: 'Business', items: ['Business management', 'Investment analysis', 'Project management'] },
      { group: 'Communication', items: ['Technical communication', 'Interviewing', 'Five languages'] },
    ],
  },
  features: {
    eyebrow: 'What I do',
    title: 'Three things',
    titleItalic: 'that drive me.',
    sub: 'Learning from the people behind the machines, understanding the physics that makes them fast, and fitting it all around an engineering degree.',
    podcast: {
      tag: 'Podcast',
      title: 'Inside The Machine',
      desc: 'Long-form conversations with drivers, collectors, designers and engineers — in English and Spanish.',
      bullets: ['{n} episodes and counting', 'Guests incl. Enzo Fittipaldi', 'YouTube · Spotify · TikTok'],
    },
    aero: {
      tag: 'Aerodynamics',
      title: 'Research & engineering',
      desc: 'My IB research paper measured how rear wing length changes downforce on a model Porsche 911 RSR.',
      bullets: ['IB Extended Essay', 'FS underfloor & diffuser — Oct 2026', 'See all research'],
      header: 'Airflow · rear wing',
      states: ['Measuring downforce', 'Adjusting wing length', 'Flow attached', 'Logging results'],
    },
    now: {
      tag: 'Right now',
      title: 'Studies + studio',
      desc: 'Engineering and business lectures at UFV, aerodynamics work with Formula Student UFV, and recording the next episode in between.',
      bullets: ['Engineering + Business minor', 'Formula Student UFV · Aero', 'Ep. 7 in production'],
      week: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
      lecture: 'Lectures',
      record: 'Recording',
      booked: 'Ep. 7 session booked',
      picking: 'Planning the week…',
    },
  },
  pillars: {
    eyebrow: 'By the numbers',
    items: [
      { label: 'Podcast episodes', end: 'episodes', suffix: '', desc: 'From Episode 0 in January to the latest release — with guests from Mexico, the US and beyond.' },
      { label: 'Languages', end: 5, suffix: '', desc: 'Grown up between Spanish and Mexican cultures, having lived in three countries early in life.' },
      { label: 'Years of community work', end: 10, suffix: '+', desc: 'Clubs, charities and foundations — including serving as President of the Global Citizens Club.' },
    ],
  },
  journey: {
    eyebrow: 'My journey',
    title: 'Three countries,',
    titleItalic: 'one constant: learning.',
    sub: 'Mexico City, Madrid — with a year in the Swiss Alps along the way — and now university. Every move a new culture and a new way of seeing things.',
    stops: [
      {
        flag: '🇲🇽',
        place: 'Mexico City, Mexico',
        chip: 'Mexico City',
        span: '8',
        unit: 'years',
        school: 'The American School Foundation',
        desc: 'Where it all started. Eight years growing up between Spanish and Mexican cultures — the roots of the perspective I bring to everything.',
        photoDesc: 'A photo from your years in Mexico — at ASF, in Mexico City, or an old family photo.',
      },
      {
        flag: '🇪🇸',
        place: 'Madrid, Spain',
        chip: 'Madrid',
        span: '10',
        unit: 'years',
        school: 'American School of Madrid',
        desc: 'A new city that became home. Ten years at the American School of Madrid — with a one-year break in Switzerland along the way — finishing with the IB Diploma in Higher Level Physics, Chemistry and Business Management, including my aerodynamics research paper.',
        link: 'Read the research paper',
        photoDesc: 'IB graduation at the American School of Madrid.',
        photos: [
          { title: 'First years at ASM', desc: 'Your first years at the American School of Madrid.', src: '/photos/madrid-early-years.jpg', pos: '50% 62%', caption: 'First years at ASM' },
          { title: 'IB graduation', src: '/photos/ib-graduation.jpg', pos: '40% 30%', caption: 'IB graduation · ASM' },
        ],
        steps: [
          { label: 'ASM', sub: '6 years' },
          { label: 'Leysin', sub: '1 year', away: true },
          { label: 'ASM', sub: '4 years · IB' },
        ],
        detour: {
          flag: '🇨🇭',
          label: 'A year away',
          back: 'Back at ASM · IB Diploma',
          chip: 'Leysin',
          place: 'Leysin, Switzerland',
          span: '1 year',
          school: 'Leysin American School',
          desc: 'Boarding school in the Swiss Alps — living independently, surrounded by students from all over the world — before coming back to Madrid.',
          photoDesc: 'You in Leysin — the campus, the mountains or classmates.',
          photo: '/photos/leysin.jpg',
          photoPos: '45% 35%',
          photoCaption: 'Leysin American School',
        },
      },
      {
        flag: '🎓',
        place: 'Madrid, Spain · Now',
        chip: 'UFV',
        span: 'UFV',
        unit: 'Now',
        now: true,
        school: 'Universidad Francisco de Vitoria',
        desc: 'Studying Automotive & Industrial Engineering with a Minor in Business Management — while working in the aerodynamics department of Formula Student UFV and building Inside The Machine alongside it.',
      },
    ],
  },
  projects: {
    eyebrow: 'Projects',
    title: 'What I’m',
    titleItalic: 'building.',
    sub: 'Real projects that show my interests and what I’m capable of creating.',
    open: 'Open',
    items: [
      { key: 'podcast', title: 'Inside The Machine Podcast', desc: 'How engineering, design and aerodynamics shape the performance and identity of cars — from road vehicles to race machines — told through the people inside motorsport.', tags: ['Audio', 'Video', 'Interviews'] },
      { key: 'paper', title: 'Aerodynamics Research', desc: 'My research papers — from my IB Extended Essay on rear-wing downforce in a model Porsche 911 RSR to an upcoming aerodynamics paper for Formula Student.', tags: ['Aerodynamics', 'Formula Student', 'Applied Physics'] },
      { key: 'fs', title: 'Formula Student UFV', desc: 'Part of the aerodynamics department of UFV’s Formula Student team, where students design, build and race their own single-seater.', tags: ['Aerodynamics', 'Teamwork', 'Motorsport'] },
      { key: 'services', title: 'Global Citizens Club & Charity', desc: 'Over a decade of clubs, charitable initiatives and foundations — including serving as President of the Global Citizens Club, connecting students with global causes and their local community.', tags: ['Leadership', 'Charity', 'Community'] },
      { key: 'sport', title: 'Karting & Football', desc: 'Competing on track and on the pitch — where discipline, focus and a competitive mindset get tested every week.', tags: ['Motorsport', 'Teamwork', 'Competition'] },
    ],
  },
  contact: {
    eyebrow: 'Contact',
    title: 'Let’s',
    titleItalic: 'talk.',
    sub: 'An idea, a collaboration, a guest suggestion for the podcast — or just to say hi.',
    emailLabel: 'Email',
    linkedinLabel: 'LinkedIn',
    instagramLabel: 'Instagram',
    note: 'Pressing send opens your email app with the message ready to go.',
    name: 'Name',
    namePh: 'Your name',
    email: 'Email',
    emailPh: 'you@email.com',
    message: 'Message',
    messagePh: 'What would you like to talk about?',
    send: 'Send message',
    sending: 'Opening your email…',
    sentTitle: 'Almost there.',
    sentDesc: 'Your email app should have opened with the message ready — just hit send there.',
    again: 'Write another message',
    missing: 'Please fill in all fields.',
  },
  footer: {
    tagline: 'Automotive & Industrial Engineering student and host of Inside The Machine.',
    status: 'Currently studying at UFV · Madrid',
    explore: 'Explore',
    podcast: 'Podcast',
    connect: 'Connect',
    rights: 'All rights reserved.',
    made: 'Always learning · Madrid',
  },
  podcastPage: {
    eyebrow: 'Podcast · Hosted by Jordi Facha Álvarez',
    line1: 'Inside',
    line2: 'The Machine.',
    sub: 'Exploring how engineering, design and aerodynamics shape the performance and identity of cars — from road vehicles to race machines — while speaking with the people inside the motorsport world.',
    watch: 'Watch on YouTube',
    listen: 'Listen on Spotify',
    site: 'Official website',
    chips: ['{n} episodes', 'English & Español'],
    newChip: 'New: Ep. {num} — {title}',
    aboutEyebrow: 'About the show',
    aboutTitle: 'Where motorsport',
    aboutTitleItalic: 'meets engineering.',
    aboutP: [
      'Inside The Machine pulls back the curtain on motorsport and car culture. Every episode digs into the technical side — the aerodynamics, the engineering decisions and the design philosophies that separate fast cars from championship-winning ones.',
      'Beyond the machines, the show features the people who live it: a three-time Carrera Panamericana winner, professional racing drivers, Ferrari collectors, automotive designers and mechanics-turned-racers.',
    ],
    stats: [
      { end: 'episodes', suffix: '', label: 'Episodes released' },
      { end: 5, suffix: '', label: 'Guests from inside the industry' },
      { end: 2, suffix: '', label: 'Languages — English & Español' },
    ],
    latestEyebrow: 'New episode',
    latestTitle: 'The latest',
    latestTitleItalic: 'episode.',
    episodeLabel: 'Episode',
    watchYt: 'Watch on YouTube',
    listenSp: 'Listen on Spotify',
    archiveEyebrow: 'Every episode',
    archiveTitle: 'The full',
    archiveTitleItalic: 'archive.',
    archiveSub: 'The three most recent episodes — open the full list for every conversation since Episode 0.',
    showAll: 'Show all episodes',
    hideAll: 'Show fewer episodes',
    followEyebrow: 'Find us on',
    followTitle: 'Listen &',
    followTitleItalic: 'follow.',
    platforms: {
      site: 'The official podcast website',
      youtube: 'Full episodes & shorts',
      spotify: 'Inside The Machine Podcast',
      tiktok: 'Clips & highlights',
      instagram: '@inside_the_machine_',
      email: 'Guest & partnership enquiries',
    },
    playTitle: 'Press',
    playTitleItalic: 'play.',
    mosaicLabel: 'Latest episodes',
  },
  researchPage: {
    eyebrow: 'Research',
    line1: 'Research',
    line2: '& papers.',
    sub: 'Aerodynamics is where engineering gets tested against the air. These are the papers where I put theory into experiments — and what I learned from them.',
    completed: 'Completed',
    inProgress: 'In progress',
    due: 'Due 18 October 2026',
    readPdf: 'Read the paper (PDF)',
    soon: 'Coming soon',
    papers: [
      {
        key: 'fs',
        status: 'progress',
        visual: 'cfd',
        context: 'Formula Student UFV · Aerodynamics department',
        title: 'Underfloor & diffuser aerodynamics of a Formula Student car',
        abstract: 'A research paper for the aerodynamics department of Formula Student UFV, focused on the car’s underfloor and diffuser — how the floor speeds up the air beneath the car to create low pressure and downforce, and how the diffuser expands that flow at the rear. Full abstract and PDF coming once it’s submitted.',
        anim: { header: 'CFD · Underfloor & diffuser', states: ['Meshing the floor', 'Flow accelerates under the floor', 'Low pressure → downforce', 'Diffuser expansion'], tag: 'Formula Student UFV', cp: 'Pressure along the floor' },
        tags: ['Underfloor', 'Diffuser', 'Ground effect', 'CFD'],
      },
      {
        key: 'ee',
        status: 'done',
        visual: 'tunnel',
        anim: { header: 'Wind tunnel · rear wing length', states: ['Run 1 · short wing', 'Run 2', 'Run 3', 'Run 4 · long wing'], tag: 'IB Extended Essay', axis: 'wing length' },
        context: 'IB Extended Essay · American School of Madrid',
        title: 'Investigating the Influence of Winglength in Aerodynamic Downforce in a Porsche 911 RSR Scale Model',
        abstract: 'My IB Extended Essay rigorously investigated how varying the length of a rear wing changes the downforce generated on a model Porsche 911 RSR — integrating aerodynamic theory with controlled experimentation to analyse performance optimisation in motorsport engineering.',
        tags: ['Aerodynamics', 'Experimentation', 'Motorsport', 'Applied Physics'],
        pdf: true,
      },
    ],
    interestsTitle: 'What I research',
    interests: ['Downforce & drag', 'Wing design', 'Experimental testing', 'Motorsport performance'],
  },
  servicesPage: {
    eyebrow: 'Global Citizens Club & Charity',
    line1: 'Building things',
    line2: 'that matter.',
    sub: 'Over a decade of involvement in clubs, charitable initiatives and foundations, including serving as President of the Global Citizens Club. This page will showcase that work.',
    soonTag: 'Coming soon',
    soonTitle: 'This page is being built.',
    soonDesc: 'Check back soon to learn more about the charitable work, initiatives and community projects I’ve been part of.',
    back: 'Back to portfolio',
    photos: [
      { title: 'Global Citizens Club', desc: 'Running a Global Citizens Club stand at school.', src: '/photos/global-citizens.jpg', pos: '70% 40%', alt: 'Jordi at a Global Citizens Club stand at school' },
      { title: 'Charity work', desc: 'Volunteering with the Banco de Alimentos (food bank).', src: '/photos/charity-food-bank.jpg', alt: 'Jordi volunteering with a group at the Banco de Alimentos food bank' },
    ],
  },
}

const es = {
  meta: {
    title: 'Jordi Facha Álvarez — Estudiante de Ingeniería y Podcaster',
    podcastTitle: 'Inside The Machine — Jordi Facha Álvarez',
    servicesTitle: 'Servicios y Comunidad — Jordi Facha Álvarez',
    researchTitle: 'Investigación — Jordi Facha Álvarez',
  },
  nav: {
    about: 'Sobre mí',
    journey: 'Trayectoria',
    projects: 'Proyectos',
    podcast: 'Podcast',
    contact: 'Contacto',
    cta: 'Contáctame',
    menu: 'Abrir menú',
    close: 'Cerrar menú',
    back: 'Volver al portfolio',
    allProjects: 'Todos los proyectos',
    menuPodcast: 'Inside The Machine',
    menuPodcastDesc: 'Podcast de motor e ingeniería',
    menuPaper: 'Investigación',
    menuPaperDesc: 'Trabajos de aerodinámica',
    research: 'Investigación',
    menuCommunity: 'Comunidad y voluntariado',
    menuCommunityDesc: 'Global Citizens Club y más',
    themeLight: 'Cambiar a modo claro',
    themeDark: 'Cambiar a modo oscuro',
  },
  photo: {
    label: 'Foto pendiente',
  },
  hero: {
    eyebrow: 'Ingeniería + Empresa · UFV Madrid',
    line1: 'Hola, soy Jordi.',
    line2: 'Ingeniería en movimiento.',
    sub: 'Estudiante de Ingeniería en Automoción e Industrial con un Minor en Administración de Empresas en la Universidad Francisco de Vitoria, miembro del departamento de aerodinámica de Formula Student UFV y presentador de Inside The Machine, un podcast sobre la ingeniería, el diseño y las personas detrás del motor.',
    ctaPrimary: 'Ver el podcast',
    ctaSecondary: 'LinkedIn',
    live: 'Nuevo',
    scroll: 'Desliza',
    photoTitle: 'Retrato principal',
    photoDesc: 'Tú con mono de carreras o chaqueta informal junto a un coche o kart, desde un ángulo ligeramente bajo y con luz de atardecer. Vertical 4:5, contigo a un lado y algo de espacio libre alrededor.',
  },
  about: {
    eyebrow: 'Sobre mí',
    title: 'Siempre aprendiendo:',
    titleItalic: 'de todo y sobre todo.',
    p: [
      'Aprender siempre ha sido el motor de todo lo que hago: me encanta aprender todo lo que puedo, sobre cualquier tema, y entender cómo funcionan realmente las cosas. Esa mentalidad me ha llevado a estudiar Ingeniería en Automoción e Industrial, con un Minor en Administración de Empresas, en la Universidad Francisco de Vitoria, en Madrid (donde también formo parte del departamento de aerodinámica de Formula Student UFV), y a buscar retos más allá de las aulas. Desde completar el Bachillerato Internacional con Física, Química y Gestión Empresarial de Nivel Superior hasta aprender cinco idiomas y lanzar un podcast de motor en el que hablo con personas de dentro de la industria, siempre he buscado oportunidades para seguir aprendiendo.',
      'Haber vivido en tres países desde pequeño y haber crecido entre las culturas española y mexicana me ha dado una visión amplia que define cómo afronto las ideas y los retos. Estar rodeado de personas con trayectorias profesionales muy diversas también me ha expuesto, desde muy joven, a distintas formas de pensar y de resolver problemas.',
      'Más allá de lo académico, me mueve la idea de crear algo con sentido. Ya sea fundando un club de inversión centrado en la IA, colaborando con organizaciones benéficas o compitiendo en fútbol y karting, valoro la disciplina, la curiosidad y la mejora continua. Estas experiencias han reforzado mi convicción de contribuir a algo más grande que yo.',
      'De cara al futuro, mi ambición es sencilla: construir, innovar y dejar un impacto duradero.',
    ],
    sign: 'Atentamente,',
    toolkitTitle: 'Herramientas',
    toolkit: [
      { group: 'Ingeniería', items: ['Aerodinámica', 'Pensamiento ingenieril', 'Experimentación'] },
      { group: 'Empresa', items: ['Gestión empresarial', 'Análisis de inversiones', 'Gestión de proyectos'] },
      { group: 'Comunicación', items: ['Comunicación técnica', 'Entrevistas', 'Cinco idiomas'] },
    ],
  },
  features: {
    eyebrow: 'Lo que hago',
    title: 'Tres cosas',
    titleItalic: 'que me mueven.',
    sub: 'Aprender de las personas detrás de las máquinas, entender la física que las hace rápidas y compaginarlo todo con un grado de ingeniería.',
    podcast: {
      tag: 'Podcast',
      title: 'Inside The Machine',
      desc: 'Conversaciones en profundidad con pilotos, coleccionistas, diseñadores e ingenieros, en inglés y en español.',
      bullets: ['{n} episodios y contando', 'Invitados como Enzo Fittipaldi', 'YouTube · Spotify · TikTok'],
    },
    aero: {
      tag: 'Aerodinámica',
      title: 'Investigación e ingeniería',
      desc: 'Mi trabajo de investigación del IB midió cómo la longitud del alerón trasero cambia la carga aerodinámica en un Porsche 911 RSR a escala.',
      bullets: ['Monografía del IB', 'Fondo plano y difusor FS, oct 2026', 'Ver toda la investigación'],
      header: 'Flujo de aire · alerón',
      states: ['Midiendo carga aerodinámica', 'Ajustando el alerón', 'Flujo adherido', 'Registrando resultados'],
    },
    now: {
      tag: 'Ahora mismo',
      title: 'Estudios + estudio',
      desc: 'Clases de ingeniería y empresa en la UFV, trabajo de aerodinámica con Formula Student UFV y, entre medias, grabando el próximo episodio.',
      bullets: ['Ingeniería + Minor en Empresa', 'Formula Student UFV · Aero', 'Ep. 7 en producción'],
      week: ['L', 'M', 'X', 'J', 'V', 'S', 'D'],
      lecture: 'Clases',
      record: 'Grabación',
      booked: 'Sesión del Ep. 7 reservada',
      picking: 'Planificando la semana…',
    },
  },
  pillars: {
    eyebrow: 'En cifras',
    items: [
      { label: 'Episodios del podcast', end: 'episodes', suffix: '', desc: 'Del Episodio 0 en enero al último lanzamiento, con invitados de México, EE. UU. y más allá.' },
      { label: 'Idiomas', end: 5, suffix: '', desc: 'Criado entre las culturas española y mexicana, tras vivir en tres países desde pequeño.' },
      { label: 'Años de trabajo comunitario', end: 10, suffix: '+', desc: 'Clubes, organizaciones benéficas y fundaciones, incluida la presidencia del Global Citizens Club.' },
    ],
  },
  journey: {
    eyebrow: 'Mi trayectoria',
    title: 'Tres países,',
    titleItalic: 'una constante: aprender.',
    sub: 'Ciudad de México, Madrid (con un año en los Alpes suizos por el camino) y ahora la universidad. Cada mudanza, una cultura nueva y una forma nueva de ver las cosas.',
    stops: [
      {
        flag: '🇲🇽',
        place: 'Ciudad de México, México',
        chip: 'Ciudad de México',
        span: '8',
        unit: 'años',
        school: 'The American School Foundation',
        desc: 'Donde empezó todo. Ocho años creciendo entre las culturas española y mexicana: la raíz de la perspectiva que aporto a todo lo que hago.',
        photoDesc: 'Una foto de tus años en México: en el ASF, en Ciudad de México o una foto familiar antigua.',
      },
      {
        flag: '🇪🇸',
        place: 'Madrid, España',
        chip: 'Madrid',
        span: '10',
        unit: 'años',
        school: 'American School of Madrid',
        desc: 'Una ciudad nueva que se convirtió en mi hogar. Diez años en el American School of Madrid, con un año de pausa en Suiza por el camino, terminando con el Bachillerato Internacional con Física, Química y Gestión Empresarial de Nivel Superior, incluido mi trabajo de investigación en aerodinámica.',
        link: 'Lee el trabajo de investigación',
        photoDesc: 'Graduación del IB en el American School of Madrid.',
        photos: [
          { title: 'Primeros años en el ASM', desc: 'Tus primeros años en el American School of Madrid.', src: '/photos/madrid-early-years.jpg', pos: '50% 62%', caption: 'Primeros años en el ASM' },
          { title: 'Graduación del IB', src: '/photos/ib-graduation.jpg', pos: '40% 30%', caption: 'Graduación del IB · ASM' },
        ],
        steps: [
          { label: 'ASM', sub: '6 años' },
          { label: 'Leysin', sub: '1 año', away: true },
          { label: 'ASM', sub: '4 años · IB' },
        ],
        detour: {
          flag: '🇨🇭',
          label: 'Un año fuera',
          back: 'De vuelta al ASM · Bachillerato IB',
          chip: 'Leysin',
          place: 'Leysin, Suiza',
          span: '1 año',
          school: 'Leysin American School',
          desc: 'Internado en los Alpes suizos: viviendo de forma independiente, rodeado de estudiantes de todo el mundo, antes de volver a Madrid.',
          photoDesc: 'Tú en Leysin: el campus, las montañas o con compañeros.',
          photo: '/photos/leysin.jpg',
          photoPos: '45% 35%',
          photoCaption: 'Leysin American School',
        },
      },
      {
        flag: '🎓',
        place: 'Madrid, España · Ahora',
        chip: 'UFV',
        span: 'UFV',
        unit: 'Ahora',
        now: true,
        school: 'Universidad Francisco de Vitoria',
        desc: 'Estudiando Ingeniería en Automoción e Industrial con un Minor en Administración de Empresas, mientras trabajo en el departamento de aerodinámica de Formula Student UFV y construyo Inside The Machine en paralelo.',
      },
    ],
  },
  projects: {
    eyebrow: 'Proyectos',
    title: 'Lo que estoy',
    titleItalic: 'construyendo.',
    sub: 'Proyectos reales que muestran mis intereses y lo que soy capaz de crear.',
    open: 'Abrir',
    items: [
      { key: 'podcast', title: 'Podcast Inside The Machine', desc: 'Cómo la ingeniería, el diseño y la aerodinámica definen el rendimiento y la identidad de los coches, de los de calle a los de competición, contado por las personas que viven el motor.', tags: ['Audio', 'Vídeo', 'Entrevistas'] },
      { key: 'paper', title: 'Investigación en aerodinámica', desc: 'Mis trabajos de investigación: desde mi Monografía del IB sobre la carga aerodinámica del alerón trasero en un Porsche 911 RSR a escala hasta un próximo trabajo de aerodinámica para Formula Student.', tags: ['Aerodinámica', 'Formula Student', 'Física aplicada'] },
      { key: 'fs', title: 'Formula Student UFV', desc: 'Miembro del departamento de aerodinámica del equipo de Formula Student de la UFV, donde los estudiantes diseñan, construyen y compiten con su propio monoplaza.', tags: ['Aerodinámica', 'Trabajo en equipo', 'Motor'] },
      { key: 'services', title: 'Global Citizens Club y voluntariado', desc: 'Más de una década en clubes, iniciativas benéficas y fundaciones, incluida la presidencia del Global Citizens Club, conectando a los estudiantes con causas globales y con su comunidad local.', tags: ['Liderazgo', 'Voluntariado', 'Comunidad'] },
      { key: 'sport', title: 'Karting y fútbol', desc: 'Compitiendo en la pista y en el campo, donde la disciplina, la concentración y la mentalidad competitiva se ponen a prueba cada semana.', tags: ['Motor', 'Trabajo en equipo', 'Competición'] },
    ],
  },
  contact: {
    eyebrow: 'Contacto',
    title: 'Hablemos',
    titleItalic: 'un rato.',
    sub: 'Una idea, una colaboración, un invitado para el podcast… o simplemente para saludar.',
    emailLabel: 'Correo',
    linkedinLabel: 'LinkedIn',
    instagramLabel: 'Instagram',
    note: 'Al pulsar enviar se abrirá tu aplicación de correo con el mensaje listo.',
    name: 'Nombre',
    namePh: 'Tu nombre',
    email: 'Correo',
    emailPh: 'tu@correo.com',
    message: 'Mensaje',
    messagePh: '¿De qué te gustaría hablar?',
    send: 'Enviar mensaje',
    sending: 'Abriendo tu correo…',
    sentTitle: 'Casi listo.',
    sentDesc: 'Tu aplicación de correo debería haberse abierto con el mensaje preparado; solo tienes que enviarlo desde ahí.',
    again: 'Escribir otro mensaje',
    missing: 'Por favor, rellena todos los campos.',
  },
  footer: {
    tagline: 'Estudiante de Ingeniería en Automoción e Industrial y presentador de Inside The Machine.',
    status: 'Estudiando en la UFV · Madrid',
    explore: 'Explorar',
    podcast: 'Podcast',
    connect: 'Conecta',
    rights: 'Todos los derechos reservados.',
    made: 'Siempre aprendiendo · Madrid',
  },
  podcastPage: {
    eyebrow: 'Podcast · Presentado por Jordi Facha Álvarez',
    line1: 'Inside',
    line2: 'The Machine.',
    sub: 'Exploramos cómo la ingeniería, el diseño y la aerodinámica definen el rendimiento y la identidad de los coches, de los de calle a los de competición, hablando con las personas que viven el mundo del motor.',
    watch: 'Ver en YouTube',
    listen: 'Escuchar en Spotify',
    site: 'Web oficial',
    chips: ['{n} episodios', 'English & Español'],
    newChip: 'Nuevo: Ep. {num} — {title}',
    aboutEyebrow: 'Sobre el programa',
    aboutTitle: 'Donde el motor',
    aboutTitleItalic: 'se encuentra con la ingeniería.',
    aboutP: [
      'Inside The Machine levanta el telón del motor y la cultura del automóvil. Cada episodio profundiza en la parte técnica: la aerodinámica, las decisiones de ingeniería y las filosofías de diseño que separan a los coches rápidos de los campeones.',
      'Más allá de las máquinas, el programa da voz a quienes lo viven: un tres veces ganador de La Carrera Panamericana, pilotos profesionales, coleccionistas de Ferrari, diseñadores de automóviles y mecánicos convertidos en pilotos.',
    ],
    stats: [
      { end: 'episodes', suffix: '', label: 'Episodios publicados' },
      { end: 5, suffix: '', label: 'Invitados de dentro de la industria' },
      { end: 2, suffix: '', label: 'Idiomas: inglés y español' },
    ],
    latestEyebrow: 'Nuevo episodio',
    latestTitle: 'El último',
    latestTitleItalic: 'episodio.',
    episodeLabel: 'Episodio',
    watchYt: 'Ver en YouTube',
    listenSp: 'Escuchar en Spotify',
    archiveEyebrow: 'Todos los episodios',
    archiveTitle: 'El archivo',
    archiveTitleItalic: 'completo.',
    archiveSub: 'Los tres episodios más recientes: abre la lista completa para ver todas las conversaciones desde el Episodio 0.',
    showAll: 'Ver todos los episodios',
    hideAll: 'Ver menos episodios',
    followEyebrow: 'Encuéntranos en',
    followTitle: 'Escucha y',
    followTitleItalic: 'síguenos.',
    platforms: {
      site: 'La web oficial del podcast',
      youtube: 'Episodios completos y shorts',
      spotify: 'Inside The Machine Podcast',
      tiktok: 'Clips y momentos destacados',
      instagram: '@inside_the_machine_',
      email: 'Invitados y colaboraciones',
    },
    playTitle: 'Dale al',
    playTitleItalic: 'play.',
    mosaicLabel: 'Últimos episodios',
  },
  researchPage: {
    eyebrow: 'Investigación',
    line1: 'Investigación',
    line2: 'y trabajos.',
    sub: 'La aerodinámica es donde la ingeniería se pone a prueba contra el aire. Estos son los trabajos en los que he llevado la teoría a experimentos, y lo que he aprendido de ellos.',
    completed: 'Completado',
    inProgress: 'En curso',
    due: 'Entrega: 18 de octubre de 2026',
    readPdf: 'Leer el trabajo (PDF)',
    soon: 'Próximamente',
    papers: [
      {
        key: 'fs',
        status: 'progress',
        visual: 'cfd',
        context: 'Formula Student UFV · Departamento de aerodinámica',
        title: 'Aerodinámica del fondo plano y el difusor de un Formula Student',
        abstract: 'Un trabajo de investigación para el departamento de aerodinámica de Formula Student UFV, centrado en el fondo plano y el difusor del coche: cómo el fondo acelera el aire bajo el coche para crear baja presión y carga aerodinámica, y cómo el difusor expande ese flujo en la parte trasera. El resumen completo y el PDF llegarán cuando se entregue.',
        anim: { header: 'CFD · Fondo plano y difusor', states: ['Mallando el fondo', 'El flujo se acelera bajo el fondo', 'Baja presión → carga', 'Expansión en el difusor'], tag: 'Formula Student UFV', cp: 'Presión a lo largo del fondo' },
        tags: ['Fondo plano', 'Difusor', 'Efecto suelo', 'CFD'],
      },
      {
        key: 'ee',
        status: 'done',
        visual: 'tunnel',
        anim: { header: 'Túnel de viento · longitud del alerón', states: ['Prueba 1 · alerón corto', 'Prueba 2', 'Prueba 3', 'Prueba 4 · alerón largo'], tag: 'Monografía del IB', axis: 'longitud' },
        context: 'Monografía del IB · American School of Madrid',
        title: 'Investigating the Influence of Winglength in Aerodynamic Downforce in a Porsche 911 RSR Scale Model',
        abstract: 'Mi Monografía del IB investigó con rigor cómo la variación de la longitud del alerón trasero cambia la carga aerodinámica generada en un Porsche 911 RSR a escala, integrando teoría aerodinámica y experimentación controlada para analizar la optimización del rendimiento en la ingeniería del motor.',
        tags: ['Aerodinámica', 'Experimentación', 'Motor', 'Física aplicada'],
        pdf: true,
      },
    ],
    interestsTitle: 'Qué investigo',
    interests: ['Carga aerodinámica y resistencia', 'Diseño de alerones', 'Ensayos experimentales', 'Rendimiento en competición'],
  },
  servicesPage: {
    eyebrow: 'Global Citizens Club y voluntariado',
    line1: 'Construyendo cosas',
    line2: 'que importan.',
    sub: 'Más de una década participando en clubes, iniciativas benéficas y fundaciones, incluida la presidencia del Global Citizens Club. Esta página recogerá ese trabajo.',
    soonTag: 'Próximamente',
    soonTitle: 'Esta página está en construcción.',
    soonDesc: 'Vuelve pronto para conocer el trabajo benéfico, las iniciativas y los proyectos comunitarios en los que he participado.',
    back: 'Volver al portfolio',
    photos: [
      { title: 'Global Citizens Club', desc: 'Con un puesto del Global Citizens Club en el colegio.', src: '/photos/global-citizens.jpg', pos: '70% 40%', alt: 'Jordi en un puesto del Global Citizens Club en el colegio' },
      { title: 'Voluntariado', desc: 'Como voluntario en el Banco de Alimentos.', src: '/photos/charity-food-bank.jpg', alt: 'Jordi como voluntario con un grupo en el Banco de Alimentos' },
    ],
  },
}

export const COPY = { en, es }
